### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by hijoncon** [morkro/atom-emoji-syntax#20]
Is typescript is be supported sooner?

**Comment by morkro** [comment]
Great idea, will work on that.

**Comment by morkro** [comment]
Hey @hijoncon,
I've added basic TypeScript support. Unfortunately the [`atom-typescript`](https://atom.io/packages/atom-typescript) package doesn't come from Atom but from TypeStrong. They don't use very detailed selectors to specify language keywords, hence the options for TypeScript are very little for now.

This is a problem with my current implementation of adding emoji and I think I would've to rewrite the entire logic of the package for better, and more detailed, keyword options. I think this is something I will tackle for a `2.0.0` release though. 😀

**Comment by hijoncon** [comment]
That's sweet @morkro thank you!  BTW I would like to contribute too
