### ISSUE TITLE
arrow function is normal function in JS

### ISSUE THREAD

**Issue by crostine** [morkro/atom-emoji-syntax#39]
I set the following emojis
🙃 arrow function
🔧 normal function
this works fine

however when I disable arrow function emojis I get the normal function emoji for the arrow function instead of no emoji.
![emoji](https://cloud.githubusercontent.com/assets/5873080/21936139/6739520e-d9b0-11e6-80ed-88f82ea1d95a.png)

**Comment by morkro** [comment]
Hey! Yes, I just fixed this issue and will publish it in about an hour. The latest Atom update changed a couple of things 😅

**Comment by morkro** [comment]
Fixed with https://github.com/morkro/atom-emoji-syntax/commit/42d43b74d9ffcc12bf87d397ef24b977cba0e27b
