### ISSUE TITLE
Add support for language-babel

### ISSUE THREAD

**Issue by screendriver** [morkro/atom-emoji-syntax#45]
![screenshot](https://cloud.githubusercontent.com/assets/149248/23398111/981c002e-fd9b-11e6-8dd9-f4b53a5cc1e2.png)

- Atom `1.14.3`
- macOS sierra `10.12.3`
- Font Family `Fira Code`
- Theme `One Dark`

**Comment by morkro** [comment]
Oh noes! Is that a JSX file by chance? If not, do you use a different `language-*` package for JavaScript?

**Comment by screendriver** [comment]
No, it's not JSX. It's a simple `*.js` file. I'm using [language-babel)](https://atom.io/packages/language-babel) as language.

**Comment by morkro** [comment]
Ah, that's it! Wasn't aware of this one.
So I have only added support for official `language-*` packages by the Atom team so far, but will add support for others as well very soon. There is also on [open request](https://github.com/morkro/atom-emoji-syntax/issues/43) for JSX and TS support.

Thanks for reporting, I will work on that :)

**Comment by morkro** [comment]
Hey @screendriver, sorry for the delay. I've just published `1.7.0` with `language-babel` support. 🎉

**Comment by screendriver** [comment]
Thank you very much :+1:
