### ISSUE TITLE
Don't show icon in .js file?

### ISSUE THREAD

**Issue by thearabbit** [morkro/atom-emoji-syntax#8]
I am a newbie with atom.
I tried to use this but don't show icon

![2016-02-16_10-37-56](https://cloud.githubusercontent.com/assets/4495160/13066519/6fc78dea-d499-11e5-98d1-8dc766ee72bb.png)

**Comment by morkro** [comment]
Hey!

Glad you're using my package. Which character did you try out though?
It looks like you're using a character which isn't supported by the font family.

**Comment by thearabbit** [comment]
In setting character is `utf8`

![2016-02-16_14-46-06](https://cloud.githubusercontent.com/assets/4495160/13070120/7f7df4b8-d4bc-11e5-979a-117a3250e9fd.png)

Which I should?

**Comment by morkro** [comment]
Oh—sorry for my confusion—the entire package doesn't work for you? All emoji's can't be displayed?

**Comment by thearabbit** [comment]
Yes, It don't displayed (show `?`).

**Comment by morkro** [comment]
Alright. I have an idea why it's not working. Do you use Windows? If yes, which version of it?

**Comment by thearabbit** [comment]
I use windows 7.

**Comment by morkro** [comment]
Cool! It looks like emoji support in Windows 7 was added in a [later update](https://support.microsoft.com/en-us/kb/2729094). Do you have the latest updates of Windows 7 installed?

**Comment by thearabbit** [comment]
So it mean I must be update my windows 7 to last via above link.

**Comment by morkro** [comment]
Yes, I would appreciate if you could install the updates for Windows 7 and tell me if that fixes the issue :) Otherwise I will take another look into the problem!

**Comment by thearabbit** [comment]
I will try.

**Comment by morkro** [comment]
Hey @thearabbit, were you able to find a solution for your problem?

**Comment by morkro** [comment]
Since there is no feedback coming anymore, I'll close this.
